CREATE TABLE YEJINJANG2(
KIM VARCHAR2(20),
JANG VARCHAR2(20),
KO VARCHAR(10), 
DIGIT NUMBER NOT NULL,
CONSTRAINT pk_YEJINJANG primary key(KIM,JANG,KO));


insert into YEJINJANG2
values('regionid','productgroup','201702',NULL);


