CREATE TABLE KOPO_EVENT_INFO_FOREIGN (
EVENTID VARCHAR2(20),
EVENTPERIOD VARCHAR2(20),
PROMOTION_RATIO NUMBER,
CONSTRAINT PK_KOPO_EVENT_INFO_FOREIGN PRIMARY KEY (EVENTID));

CREATE TABLE KOPO_PRODUCT_VOLUME_FOREIGN(
REGIONID VARCHAR2(20),
PRODUCTGROUP VARCHAR2(20),
YEARWEEK VARCHAR2(8),
VOLUME NUMBER NOT NULL, 
EVENTID VARCHAR2(20),
CONSTRAINT PK_KOPO_PRODUCT_VOLUME_FOREIGN PRIMARY KEY(REGIONID, PRODUCTGROUP, YEARWEEK),
CONSTRAINT FK_KOPO_PRODUCT_VOLUME_FOREIGN FOREIGN KEY(EVENTID) REFERENCES KOPO_EVENT_INFO_FOREIGN (EVENTID)
ON DELETE CASCADE -- 처음 데이터 생성시에 마지막줄에 써주든지 
);

ALTER TABLE KOPO_PRODUCT_VOLUME_FOREIGN --나중에 ALTER TABLE에 써줌
DROP CONSTRAINT FK_KOPO_PRODUCT_VOLUME_FOREIGN;

ALTER TABLE KOPO_PRODUCT_VOLUME_FOREIGN
ADD CONSTRAINT FK_KOPO_PRODUCT_VOLUME_FOREIGN
    FOREIGN KEY(EVENTID)
    REFERENCES KOPO_EVENT_INFO_FOREIGN(EVENTID)
    ON DELETE CASCADE;


SELECT * FROM KOPO_PRODUCT_VOLUME_FOREIGN;


INSERT INTO KOPO_EVENT_INFO_FOREIGN
VALUES('EV001','201634',100);


INSERT INTO KOPO_PRODUCT_VOLUME_FOREIGN
VALUES('A02','ST00003','201504',50,'EV001'); --부모테이블에 값이 없는데 자식테이블에 값을 넣으면 안돼
                                              --이 값을 넣고 싶으면, 참조하는 부모테이블에 EVENTID 가 EVTEST인 기본키를 먼저 넣어줘

INSERT INTO KOPO_EVENT_INFO_FOREIGN
(EVENTID,EVENTPERIOD) --컬럼 중 몇 가지 항목만 넣고 싶다면, INSERT INTO 뒤에 해당 컬럼을 써  
VALUES('E12','201825');

SELECT * FROM KOPO_EVENT_INFO_FOREIGN;

SELECT * FROM KOPO_PRODUCT_VOLUME_FOREIGN;

DELETE FROM KOPO_EVENT_INFO_FOREIGN WHERE EVENTID='EV001'; --자식테이블이 참조하고 있는데 부모테이블에서 데이터 삭제하려니 에러가 남 
                                                           -- 1.자식테이블에서 해당 데이터 삭제후, 2.부모테이블에서 삭제
                                                           
DESC KOPO_PRODUCT_VOLUME_FOREIGN; --TABLE 정보 확인
