CREATE TABLE KOPO_PRODUCT_VOLUME_HR5(
    REGIONID VARCHAR2(20),
    PRODUCTGROUP VARCHAR2(20),
    YEARWEEK VARCHAR2(20),
    QTY NUMBER
);

SELECT * FROM KOPO_PRODUCT_VOLUME_HR5;

INSERT INTO KOPO_PRODUCT_VOLUME_HR5
 VALUES('A01', 'ST0001','201701',50);
 
SELECT * FROM KOPO_PRODUCT_VOLUME_HR5;
 
ALTER TABLE KOPO_PRODUCT_VOLUME_HR5
 ADD CONSTRAINTS KOPO_PRODUCT_VOLUME_HR5_PK
 PRIMARY KEY(REGIONID, PRODUCTGROUP, YEARWEEK);
 
SELECT * FROM KOPO_PRODUCT_VOLUME_HR5;
  
--TRUNCATE TABLE KOPO_PRODUCT_VOLUME_HR5;

SELECT * FROM KOPO_PRODUCT_VOLUME_HR5;


CREATE TABLE REGION_MASTER_HR1(
    REGIONID VARCHAR2(20),
    REGIONNAME VARCHAR2(20)
);

INSERT INTO REGION_MASTER_HR1
    VALUES('B01','한국');

INSERT INTO REGION_MASTER_HR1
    VALUES('B02','미국');
    
    
INSERT INTO REGION_MASTER_HR1
    VALUES('B03','영국');
    
SELECT * FROM REGION_MASTER_HR1;