--테이블 생성
create table KOPO_PRODUCT_VOLUME_HR3(
    REGIONID VARCHAR2(20),
    PRODUCTGROUP VARCHAR2(20),
    YEARWEEK VARCHAR2(20),
    QTY NUMBER);
   
--자바 파일로 돌리기 위해서 하나 더 만든 파일 
CREATE TABLE REGION_MASTER_HR3(
    REGIONID VARCHAR2(100),
    REGIONNAME VARCHAR2(100)
    );

--------EDIT 로 입력하는 것도 있지만, 처음부터 그렇게 하는 사람은 없음
INSERT INTO REGION_MASTER_HR3
    VALUES ('A01','미국');

INSERT INTO REGION_MASTER_HR3
    VALUES ('A02','한국');


SELECT * FROM REGION_MASTER_HK;


--데이터 삽입
INSERT INTO KOPO_PRODUCT_VOLUME_HR3
    VALUES('A01', 'ST0001','201701',50);
    
ALTER TABLE KOPO_PRODUCT_VOLUME_HR3
    ADD CONSTRAINTS KOPO_PRODUCT_VOLUME_HR3_PK
    PRIMARY KEY(REGIONID, PRODUCTGROUP, YEARWEEK);
 
EDIT REGION_MASTER_HK;
   


--테이블 구조 변경
ALTER TABLE KOPO_PRODUCT_VOLUME_HR3
    DROP CONSTRAINTS KOPO_PRODUCT_VOLUME_HR3;
    
--데이터 삭제
TRUNCATE TABLE KOPO_PRODUCT_VOLUME_HR3;



--데이터 보기
SELECT * FROM KOPO_PRODUCT_VOLUME_HR3;

SELECT * FROM REGION_MASTER_HR3;
    

    